### ISSUE TITLE
Suggestion: Remove App component

### ISSUE THREAD

**Issue by roblafeve** [cremalab/crema-components#17]
I suggest we remove the App component since we have storybook. I can see how this is a place where we can "prove" that components are consumable, but we can achieve the same thing by sourcing our stories and tests from the `index.ts` file in each component.

If we don't remove `App` then I suggest we ignore it in coverage.

**Comment by belv2c** [comment]
@roblafeve good idea!

**Comment by thispastwinter** [comment]
Yes please

**Comment by thispastwinter** [comment]
I've created this PR to address just that! https://github.com/cremalab/crema-components/pull/19
